[Service]
WorkingDirectory=/home/ajmalrasi/tensorrt-json-schema-release-2cb8bb8/source
Environment=EDGELLM_PYBIND_DIR=/home/ajmalrasi/tensorrt-json-schema-release-2cb8bb8/pybind
Environment=EDGELLM_CONTINUOUS_GRAPHS=0
Environment=LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu:/usr/local/cuda/targets/sbsa-linux/lib
